---
# JHOVE installation for ddhn.tools

- name: "DROID | Running Tool Setup."
  include_tasks: tool.yml
  vars:
    item: "{{ ddhn.tools.droid }}"

- name: "DROID | Download and upack installer."
  unarchive:
    src: "{{ ddhn.tools.droid.installer.loc }}"
    dest: "{{ ddhn.tools.droid.dests.lib }}"
    remote_src: yes

- name: "DROID | Create symlink for shell file."
  file:
    src: "{{ ddhn.tools.droid.dests.lib }}/droid.sh"
    dest: "{{ ddhn.tools.droid.dests.bin }}/droid-gui"
    state: link
