---
# veraPDF installation for ddhn.tools

- name: "veraPDF | Running Tool Setup."
  include_tasks: tool.yml
  vars:
    item: "{{ ddhn.tools.verapdf }}"

- name: "veraPDF | Create installer root."
  file:
    path: "{{ ddhn.tools.verapdf.installer.root }}"
    state: directory
    mode: '0755'

- name: "veraPDF | Download and upack installer."
  unarchive:
    src: "{{ ddhn.tools.verapdf.installer.loc }}"
    dest: "{{ ddhn.tools.verapdf.installer.root }}"
    remote_src: yes

- name: "veraPDF | Copy custom installation config."
  template:
    src: "tmp/verapdf-install.xml"
    dest: "/tmp/verapdf-install.xml"

- name: "veraPDF | Run installation script"
  command: "{{ ddhn.tools.verapdf.installer.script }} /tmp/verapdf-install.xml"

- name: "veraPDF | Create symlink for CLI shell file."
  file:
    src: "{{ ddhn.tools.verapdf.dests.lib }}/verapdf"
    dest: "{{ ddhn.tools.verapdf.dests.bin }}/verapdf"
    state: link

- name: "veraPDF | Create symlink for GUI shell file."
  file:
    src: "{{ ddhn.tools.verapdf.dests.lib }}/verapdf-gui"
    dest: "{{ ddhn.tools.verapdf.dests.bin }}/verapdf-gui"
    state: link
