---
# Main task entry point for opf.proxy

- name: "IMPORT | NGINX installation using official role."
  import_role:
    name : nginxinc.nginx
  vars:
    branch: "{{ opf.nginx.branch }}"

- name: "IMPORT | NGINX configuration."
  import_tasks: nginx.yml
