---
# Main task entry point for opf.proxy

- name: "NGINX | Create sites-available directory."
  file:
    path: "{{ opf.nginx.sites_available }}"
    state: directory
    mode: 0644

- name: "NGINX | Create sites-enabled directory."
  file:
    path: "{{ opf.nginx.sites_enabled }}"
    state: directory
    mode: 0644

- name: "NGINX | Check default config file exists"
  stat:
    path: "{{ opf.nginx.default_site_conf }}"
  register: default_site_stat

- name: "NGINX | Move default.conf nginx site to site-available."
  command: "mv {{ opf.nginx.default_site_conf }} {{ opf.nginx.sites_available }}/default"
  when: default_site_stat.stat.exists

- name: "NGINX | Create sites-enabled symlink for default"
  file:
    path: "{{ opf.nginx.sites_enabled }}/default"
    src: "{{ opf.nginx.sites_available }}/default"
    state: link
  notify:
    - restart nginx
  when: opf.nginx.default_site == true and default_site_stat.stat.exists

- name: "NGINX | Add hostname to default nginx file."
  replace:
    path: /usr/share/nginx/html/index.html
    regexp: 'nginx!'
    replace: 'nginx on {{ opf_server_fqdn }}!'

- name: "NGINX | Add optimized nginx.conf."
  copy:
    src: "files/etc/nginx/nginx.conf"
    dest: "{{ opf.nginx.default_conf }}"
    mode: 0644
  notify:
    - restart nginx
