---
# desktop Environment setup for DDHN tools

- name: "Desktop | Enable desktop icons"
  become: true
  become_user: "{{ ddhn.setup.limited_account.name }}"
  shell: |
    dbus-launch gsettings set org.gnome.desktop.background show-desktop-icons true
