---
# Main task entry point for ddhn.setup

- name: "DDHN SETUP | Update host OS and setup server."
  import_tasks: server.yml

- name: "DDHN SETUP | Install prerequisites."
  import_tasks: prerequisites.yml

- name: "DDHN SETUP | Set up user account with SSH key."
  import_tasks: user.yml

- name: "DDHN SETUP | Secure server."
  import_tasks: security/main.yml

- name: "DDHN SETUP | Setup desktop environment."
  import_tasks: desktop.yml
