---
# opf.proxy default values

opf_nginx_root: "/etc/nginx/"
opf:
  nginx:
    port:
      http: "{{ opf_server_port_http | default('') }}"
      https: "{{ opf_server_port_https | default('') }}"
    branch: "{{ opf_nginx_branch | default('stable') }}"
    default_conf: "{{ opf_nginx_root }}/nginx.conf"
    default_site: "{{ opf_nginx_default_site | default(true) }}"
    default_site_conf: "{{ opf_nginx_root }}/conf.d/default.conf"
    sites_available: "{{ opf_nginx_root }}/sites-available"
    sites_enabled: "{{ opf_nginx_root }}/sites-enabled"
    log_dir: "{{ opf_server_log | default('/var/log') }}/nginx"
