# opf.proxy metadata
---
galaxy_info:
  author: "Carl Wilson"
  company: "Open Preservation Foundation"
  description: "Installs and configures an OPF NGINX server on Debian 9."
  license: GPL v3
  min_ansible_version: 2.0.0
  platforms:
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - OPF
    - NGINX
